name: CityWeaver

options:
  bundleIdPrefix: com.janstusio.cityweaver
  minimumXcodeGenVersion: 2.10
  deploymentTarget:
    macOS: "15.0"
  defaultConfig: Debug
  localPackagesGroup: "Packages"

configs:
  Debug: debug
  Release: release

# Local Swift Packages
packages:
  Core:
    path: ./Packages/Core
    group: "Packages"
  Shared:
    path: ./Packages/Shared
    group: "Packages"
  RGA:
    path: ./Packages/RGA
    group: "Packages"
  Terrain:
    path: ./Packages/Terrain
    group: "Packages"

# Project-level settings
settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"

targets:
  # macOS App Target
  CityWeaverMac:
    type: application
    platform: macOS
    sources:
      - path: App
        excludes:
          - "**/.DS_Store"
          - "**/Thumbs.db"
    dependencies:
      - package: Core
      - package: Shared
      - package: RGA
      - package: Terrain
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.janstusio.cityweaver.app
        INFOPLIST_FILE: App/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 9SA9YW222L
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          SWIFT_OPTIMIZATION_LEVEL: -Onone
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
          SWIFT_OPTIMIZATION_LEVEL: -O
    scheme:
      gatherCoverageData: true

# Custom schemes for different environments
schemes:
  CityWeaver Debug:
    build:
      targets:
        CityWeaverMac: all
    run:
      config: Debug
      environmentVariables:
        APP_ENV: DEBUG
        OS_ACTIVITY_MODE: disable

  CityWeaver Release:
    build:
      targets:
        CityWeaverMac: all
    run:
      config: Release
      environmentVariables:
        APP_ENV: RELEASE
    archive:
      config: Release

# File groups for organization
fileGroups:
  - README.md
  - project.yml
  - .gitignore
  - makefile
  - doc/architecture.md

# Setting groups for reusability
settingGroups:
  common_swift:
    SWIFT_VERSION: "6.0"
    ENABLE_STRICT_OBJC_MSGSEND: YES
    CLANG_ENABLE_OBJC_ARC: YES
    CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
    CLANG_WARN_BOOL_CONVERSION: YES
    CLANG_WARN_COMMA: YES
    CLANG_WARN_CONSTANT_CONVERSION: YES
    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
    CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
    CLANG_WARN_DOCUMENTATION_COMMENTS: YES
    CLANG_WARN_EMPTY_BODY: YES
    CLANG_WARN_ENUM_CONVERSION: YES
    CLANG_WARN_INFINITE_RECURSION: YES
    CLANG_WARN_INT_CONVERSION: YES
    CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
    CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
    CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
    CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
    CLANG_WARN_STRICT_PROTOTYPES: YES
    CLANG_WARN_SUSPICIOUS_MOVE: YES
    CLANG_WARN_UNGUARDED_AVAILABILITY: YES_AGGRESSIVE
    CLANG_WARN_UNREACHABLE_CODE: YES
    CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
    GCC_WARN_64_TO_32_BIT_CONVERSION: YES
    GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
    GCC_WARN_UNDECLARED_SELECTOR: YES
    GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
    GCC_WARN_UNUSED_FUNCTION: YES
    GCC_WARN_UNUSED_VARIABLE: YES

  debug_settings:
    DEBUG_INFORMATION_FORMAT: dwarf
    ENABLE_TESTABILITY: YES
    GCC_OPTIMIZATION_LEVEL: "0"
    ONLY_ACTIVE_ARCH: YES
    SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    SWIFT_OPTIMIZATION_LEVEL: -Onone

  release_settings:
    DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
    ENABLE_NS_ASSERTIONS: NO
    SWIFT_COMPILATION_MODE: wholemodule
    SWIFT_OPTIMIZATION_LEVEL: -O
    VALIDATE_PRODUCT: YES
